
--Javierl las 2, 4, 14, 15, 16, 17?
--2) Dar el nombre del proveedor y los productos que él haya provisto,
-- donde por lo menos tenga 3 de sus producto que estén en una o mar órdenes.
SELECT S.COMPANYNAME, P.PRODUCTNAME, COUNT(O.ORDERID) AS NUMERO_ORDENES
FROM ORDERS O INNER JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
INNER JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
INNER JOIN SUPPLIES S ON P.SUPPLIERID =  S.SUPPLIERID
WHERE NUMERO_ORDENES > 3;
------------ MANERA MEDIO CORRECTA
SELECT S.COMPANYNAME, P.PRODUCTNAME, OD.QUANTITY AS QUANTITY_FOR_ORDER
FROM ORDERS O INNER JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
INNER JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
INNER JOIN SUPPLIERS S ON P.SUPPLIERID =  S.SUPPLIERID
WHERE OD.QUANTITY > 3
ORDER BY S.COMPANYNAME, P.PRODUCTNAME, OD.QUANTITY DESC;



--4) Dar el nombre de todos los clientes que ha recibido sus paquetes por el
-- transportista “Speedy Express”, y que haya sido atendido por un empleado que no
-- tenga mando.
--*************************************************************************
-- CONSULTAR SOBRE POR QUE NO HAY SHIPPERID EN ORDERS PERO PUEDE SER SHIPVIA
SELECT C.COMPANYNAME AS "NOMBRE DEL CLIENTE", SH.COMPANYNAME AS "NOMBRE DEL TRANSPORTISTA" 
FROM EMPLOYEES E INNER JOIN ORDERS O ON E.EMPLOYEEID =  O.EMPLOYEEID 
INNER JOIN SHIPPERS S ON O.SHIPPERID = S.SHIPPERID
WHERE S.COMPANYNAME = 'Speedy Express' AND 
E.REPORTSTO IS NULL;
 ----------------------------MANERA CORRECTA
 SELECT C.COMPANYNAME AS NOMBRE_DEL_CLIENTE, S.COMPANYNAME AS NOMBRE_DEL_TRANSPORTISTA, E.FIRSTNAME ||' '||E.LASTNAME, E.REPORTSTO
FROM EMPLOYEES E INNER JOIN ORDERS O ON E.EMPLOYEEID =  O.EMPLOYEEID 
INNER JOIN SHIPPERS S ON O.SHIPVIA = S.SHIPPERID
INNER JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID
WHERE E.REPORTSTO IS NULL AND
S.COMPANYNAME = 'Speedy Express';







--14) Cree un script que muestre nombre del cliente que haya tenido más pedidos
-- que todos los demás clientes.
SELECT C.COMPANYNAME AS "NOMBRE DEL CLIENTE", COUNT(O.ORDERID) AS "TOTAL DE ORDENES"
FROM   ORDERS O, CUSTOMERS C
WHERE O.CUSTOMERID =  C.CUSTOMERID
LIMIT 1;
--MANERA CORRECTA
--Intentar hacerlo en el WHERE por que al inge no le gusta en el FROM
SELECT *
FROM(
    SELECT C.COMPANYNAME AS NOMBRE_DEL_CLEINTE, COUNT(O.ORDERID) AS TOTAL_DE_ORDENES
    FROM ORDERS O, CUSTOMERS C
    WHERE O.CUSTOMERID =  C.CUSTOMERID
    GROUP BY C.COMPANYNAME
    ORDER BY TOTAL_DE_ORDENES DESC
) TOP_LIST
WHERE ROWNUM = 1;





--15) Dar el nombre del cliente y el nombre del producto con su código, más comprado.
--DE TODAS LAS ORDEENES EL PRODUC MAS VENDIDO  Y PONER EL NOMBRE DEL CUSTOMER`
----Consultar como es el problema
SELECT C.COMPANYNAME AS "NOMBRE DEL CLIENTE", P.PRODUCTNAME, P.PRODUCTID
FROM CUSTOMERS C INNER JOIN ORDERS O ON C.CUSTOMERID =  O.CUSTOMERID
INNER JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
INNER JOIN PRODUCTS P ON OD.PRODUCTID =  P.PRODUCTID
WHERE O.CUSTOMERID =  C.CUSTOMERID
LIMIT 1;






--16) Dar el nombre de los 5 clientes quienes más dinero gastaron junto con los cinco
-- clientes que menos gastaron, cree una columna que indique si corresponde a los
-- que más o menos gastaron.
--CONSULTAR COMO HACER LA NUEVA COLUMNA
SELECT C.COMPANYNAME , SUM(TO_NUMBER(OD.UNITPRICE) * TO_NUMBER(OD.QUANTITY)) AS "GASTO_TOTAL", 
FROM ORDERDETAILS OD INNER JOIN ORDENES O ON OD.ORDERID = O.ORDERID
INNER JOIN CUSTOMERS C ON O.CUSTOMERID  = C.CUSTOMERID
ORDER BY GASTO_TOTAL DESC
LIMIT 5;

 




--17) Dar el nombre y apellido del Jefe de los empleados que haya obtenido más ordenes
-- realizadas y que en esas órdenes tuvieron que haber vendido al menos 5
-- productos en cada orden.
--PREGUNTARA SOBRE EL ORDEN DE LSO WHERE EN CASO DE QUE EL MAS QUE˜NO NO SEA EL QUE SIGE
SELECT B.FISTNAME, B.LASTNAME, E.FISTNAME, E.LASTNAME, COUNT(O.ORDERID) AS "NUMERO_ORDENES"
FROM EMPLOYEES E, EMPLOYEES B, ORDERDETAILS OD, ORDERS O
WHERE E.EMPLOYEEID = B.EMPLOYEEID AND
O.EMPLOYEEID = E.EMPLOYEEID AND
OD.ORDERID = O.ORDERID AND
OD.QUANTITY > 5
------------MANERA MEDIO CORRECTA
SELECT B.FIRSTNAME NOMNRE_JEFE, B.LASTNAME APELLIDO_JEFE, E.FIRSTNAME AS NOMBRE_EMPLEADO, COUNT(O.ORDERID) AS NUMERO_ORDENES
FROM EMPLOYEES B 
INNER JOIN EMPLOYEES E ON B.EMPLOYEEID = E.EMPLOYEEID
INNER JOIN ORDERS O ON E.EMPLOYEEID = O.EMPLOYEEID
INNER JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
WHERE OD.QUANTITY > 5
GROUP BY B.FIRSTNAME, B.LASTNAME
ORDER BY NUMERO_ORDENES DESC;










----------------CLASE 13 OCTUBRE EJERCICIO---------------
SELECT
FROM ORDERS O, CUSTOMERS C
WHERE 20 >(
            SELECT OD.QUANTITY
            FROM ORDERDETAILS OD, PRODUCT P
            WHERE 
            OD.ORDERID = O.ORDERID AND
            OD.PRODUCTID = P.PRODUCTID AND 
            P.PRODUCTID = 23

)

SELECT
FROM ORDERDETAILS OD, PRODUCT P
WHERE 
OD.PRODUCTID = P.PRODUCTID
P.PRODUCTID = 23