
--Javierl las 2, 4, 14, 15, 16, 17?
--2) Dar el nombre del proveedor y los productos que él haya provisto,
-- donde por lo menos tenga 3 de sus producto que estén en una o mar órdenes.
SELECT S.COMPANYNAME, P.PRODUCTNAME, COUNT(O.ORDERID) AS NUMERO_ORDENES
FROM ORDERS O INNER JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
INNER JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
INNER JOIN SUPPLIES S ON P.SUPPLIERID =  S.SUPPLIERID
WHERE NUMERO_ORDENES > 3;
------------ MANERA MEDIO CORRECTA
SELECT  S.COMPANYNAME, P.PRODUCTNAME, OD.QUANTITY AS QUANTITY_FOR_ORDER, O.ORDERID
FROM ORDERS O INNER JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
INNER JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
INNER JOIN SUPPLIERS S ON P.SUPPLIERID =  S.SUPPLIERID
WHERE OD.QUANTITY > 3
ORDER BY O.ORDERID, S.COMPANYNAME, P.PRODUCTNAME, OD.QUANTITY DESC;



--4) Dar el nombre de todos los clientes que ha recibido sus paquetes por el
-- transportista “Speedy Express”, y que haya sido atendido por un empleado que no
-- tenga mando.
--*************************************************************************
-- CONSULTAR SOBRE POR QUE NO HAY SHIPPERID EN ORDERS PERO PUEDE SER SHIPVIA
SELECT C.COMPANYNAME AS "NOMBRE DEL CLIENTE", SH.COMPANYNAME AS "NOMBRE DEL TRANSPORTISTA" 
FROM EMPLOYEES E INNER JOIN ORDERS O ON E.EMPLOYEEID =  O.EMPLOYEEID 
INNER JOIN SHIPPERS S ON O.SHIPPERID = S.SHIPPERID
WHERE S.COMPANYNAME = 'Speedy Express' AND 
E.REPORTSTO IS NULL;
 ----------------------------MANERA CORRECTA
 SELECT C.COMPANYNAME AS NOMBRE_DEL_CLIENTE, S.COMPANYNAME AS NOMBRE_DEL_TRANSPORTISTA, E.FIRSTNAME ||' '||E.LASTNAME, E.REPORTSTO
FROM EMPLOYEES E INNER JOIN ORDERS O ON E.EMPLOYEEID =  O.EMPLOYEEID 
INNER JOIN SHIPPERS S ON O.SHIPVIA = S.SHIPPERID
INNER JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID
WHERE E.REPORTSTO IS NULL AND
S.COMPANYNAME = 'Speedy Express';







--14) Cree un script que muestre nombre del cliente que haya tenido más pedidos
-- que todos los demás clientes.
SELECT C.COMPANYNAME AS "NOMBRE DEL CLIENTE", COUNT(O.ORDERID) AS "TOTAL DE ORDENES"
FROM   ORDERS O, CUSTOMERS C
WHERE O.CUSTOMERID =  C.CUSTOMERID
LIMIT 1;
--MANERA CORRECTA
--Intentar hacerlo en el WHERE por que al inge no le gusta en el FROM
SELECT *
FROM(
    SELECT C.COMPANYNAME AS NOMBRE_DEL_CLEINTE, COUNT(O.ORDERID) AS TOTAL_DE_ORDENES
    FROM ORDERS O, CUSTOMERS C
    WHERE O.CUSTOMERID =  C.CUSTOMERID
    GROUP BY C.COMPANYNAME
    ORDER BY TOTAL_DE_ORDENES DESC
) TOP_LIST
WHERE ROWNUM = 1;
-------or

SELECT C.CONTACTNAME AS NOMBRE_DEL_CLIENTE, COUNT(O.ORDERID) AS TOTAL_DE_ORDENES
FROM ORDERS O, CUSTOMERS C
WHERE O.CUSTOMERID =  C.CUSTOMERID
GROUP BY C.CONTACTNAME
ORDER BY TOTAL_DE_ORDENES DESC
FETCH FIRST ROW ONLY




--15) Dar el nombre del cliente y el nombre del producto con su código, más comprado.
--DE TODAS LAS ORDEENES EL PRODUC MAS VENDIDO  Y PONER EL NOMBRE DEL CUSTOMER`
----Consultar como es el problema
--MANERA CORRECA
SELECT C.CONTACTNAME, P.PRODUCTNAME, P.PRODUCTID, SUM(OD.QUANTITY) AS CANTIDAD_VENDIDA
FROM CUSTOMERS C INNER JOIN ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
INNER JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
INNER JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
GROUP BY C.CONTACTNAME, P.PRODUCTNAME, P.PRODUCTID
ORDER BY SUM(OD.QUANTITY) DESC
FETCH FIRST 2 ROW ONLY;







--16) Dar el nombre de los 5 clientes quienes más dinero gastaron junto con los cinco
-- clientes que menos gastaron, cree una columna que indique si corresponde a los
-- que más o menos gastaron.
--CONSULTAR COMO HACER LA NUEVA COLUMNA
SELECT C.COMPANYNAME , SUM(TO_NUMBER(OD.UNITPRICE) * TO_NUMBER(OD.QUANTITY)) AS "GASTO_TOTAL", 
FROM ORDERDETAILS OD INNER JOIN ORDENES O ON OD.ORDERID = O.ORDERID
INNER JOIN CUSTOMERS C ON O.CUSTOMERID  = C.CUSTOMERID
ORDER BY GASTO_TOTAL DESC
LIMIT 5;

 




--17) Dar el nombre y apellido del Jefe de los empleados que haya obtenido más ordenes
-- realizadas y que en esas órdenes tuvieron que haber vendido al menos 5
-- productos en cada orden.
--PREGUNTARA SOBRE EL ORDEN DE LSO WHERE EN CASO DE QUE EL MAS QUE˜NO NO SEA EL QUE SIGE
------------MANERA  CORRECTA
SELECT B.FIRSTNAME||' '|| B.LASTNAME AS NOMBRE_COMPLETO_JEFE, E.FIRSTNAME AS NOMBRE_EMPLEADO, COUNT(O.ORDERID) AS NUMERO_ORDENES
FROM EMPLOYEES B 
INNER JOIN EMPLOYEES E ON B.EMPLOYEEID = E.EMPLOYEEID
INNER JOIN ORDERS O ON E.EMPLOYEEID = O.EMPLOYEEID
INNER JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
WHERE OD.QUANTITY > 5
GROUP BY B.FIRSTNAME||' '|| B.LASTNAME, E.FIRSTNAME
ORDER BY NUMERO_ORDENES DESC;










----------------CLASE 13 OCTUBRE EJERCICIO---------------
SELECT
FROM ORDERS O, CUSTOMERS C
WHERE 20 >(
            SELECT OD.QUANTITY
            FROM ORDERDETAILS OD, PRODUCT P
            WHERE 
            OD.ORDERID = O.ORDERID AND
            OD.PRODUCTID = P.PRODUCTID AND 
            P.PRODUCTID = 23

)

SELECT
FROM ORDERDETAILS OD, PRODUCT P
WHERE 
OD.PRODUCTID = P.PRODUCTID
P.PRODUCTID = 23

---------CLASE 15 OCTUBRE ------
--dar el nombre de los empleados que reciben reporres (jefes)
--SUBCONSULTA
SELECT EMPLOYEEID
FROM EMPLOYEES
WHERE EMPLOYEEID IS NOT NULL
--CONSULTA PRUNCIPAL
SELECT E.FIRSTNAME||' '||E.LASTNAME
FROM EMPLOYEES E
WHERE E.EMPLOYEEID IN (
                        SELECT EMPLOYEEID
                        FROM EMPLOYEES
                        WHERE EMPLOYEEID IS NOT NULL
)
ORDER BY E.FIRSTNAME||' '||E.LASTNAME

--DAR EL NOMBRE PRODUCTO CON EL PRESION MAS BAJO
--SUBCONSULTA
SELECT MIN(UNITPRICE)
FROM PRODUCTS
--PRINCIPAL
SELECT P.PRODUCTNAME
FROM PRODUCTS P
WHERE P.UNITPRICE =(
                      SELECT MIN(UNITPRICE)
                      FROM PRODUCTS
                    )

--DAR EL NOMBRE DEL PRODUCTO VENDIDO A UN PRECIO DIFERENTE AL DEFINIDO
--SUBOSNUTLA
SELECT P.PRODUCTID
FROM PRODUCTS P INNER JOIN OERDERDETAILS OD ON
P.PRODUCTID = OD.PRODUCTID 
WHERE P.UNITPRICE != OD.UNITPRICE

--CONSULTA
SELECT PRODUCTNAME
FROM PRODUCTS
WHERE PRODUCTID IN (
                    SELECT P.PRODUCTID
                    FROM PRODUCTS P INNER JOIN ORDERDETAILS OD ON
                    P.PRODUCTID = OD.PRODUCTID 
                    WHERE P.UNITPRICE != OD.UNITPRICE
)


--CONSULTA
SELECT P1.PRODUCTNAME
FROM PRODUCTS P1, ORDERDETAILS OD
WHERE PRODUCTID IN (
                    SELECT P.PRODUCTID
                    FROM PRODUCTS P INNER JOIN ORDERDETAILS OD ON
                    P.PRODUCTID = OD.PRODUCTID 
                    WHERE P.UNITPRICE != OD.UNITPRICE
)



--DAR EL NOMBRE DEL PROVEEDOR DONDE SU PRODUCTO HAYA SIDO COMPRADO
--SUB
SELECT S.COMPANYNAME
FROM SUPPLIERS S INNER JOIN PRODUCTS P ON S.SUPPLIERID = P.SUPPLIERID
INNER JOIN ORDERDETAILS OD ON P.PRODUCTID = OD.PRODUCTID
WHERE OD.PRODUCTID IS NOT NULL AND
OD.QUANTITY > 0;